version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db,
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=testdb
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
