name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: docker_build
        run: |
          IMAGE_NAME=syedamaseera/my-node-app
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|image:.*|image: syedamaseera/my-node-app:${{ github.sha }}|g" ./k8s-manifest/app-deployment.yml
          git add ./k8s-manifest/app-deployment.yml
          git commit -m "Update image tag to ${{ github.sha }}"


      - name: Push changes back to the repository
        run: git push
      
      