apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: argocd  # Added namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: syedamaseera/my-node-app:59c879d9a7e51e50ac634c3e2d08ca19f4e6a9d6
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DB
              value: "testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080

